version: "3.0"
services:
  Sanic3.8:
    image: sanic-py-3.8
    build: 
      context: ..
      dockerfile: SanicApp/dockerfile
      args: 
        VERSION: 3.8
    ports:
      - 7003:7000
      - 6003:6000
    environment:
        REVDEBUG_HOST: ${REVDEBUG_HOST:-20.199.127.147}
        DB_TEST_HOST: ${DB_TEST_HOST:-}
        DB_TEST_PORT: ${DB_TEST_PORT:-5432}
        DB_TEST_USER: ${DB_TEST_USER:-rdb_user}
        DB_TEST_PASS: ${DB_TEST_PASS:-masterkey}
        DB_TEST_DB: ${DB_TEST_DB:-revdebug_db}
        REVDEBUG_SOLUTION: SanicTest3.8
        REVDEBUG_APPLICATION: SanicTest3.8
    volumes:
      - ../:/app
  Sanic3.9:
    image: sanic-py-3.9
    build: 
      context: ..
      dockerfile: SanicApp/dockerfile
      args: 
        VERSION: 3.9
    environment:
        REVDEBUG_HOST: ${REVDEBUG_HOST:-51.103.82.86}
        DB_TEST_HOST: ${DB_TEST_HOST:-}
        DB_TEST_PORT: ${DB_TEST_PORT:-5432}
        DB_TEST_USER: ${DB_TEST_USER:-rdb_user}
        DB_TEST_PASS: ${DB_TEST_PASS:-masterkey}
        DB_TEST_DB: ${DB_TEST_DB:-revdebug_db}
        REVDEBUG_SOLUTION: SanicTest3.9
        REVDEBUG_APPLICATION: SanicTest3.9
    ports:
      - 7004:7000
      - 6004:6000
    volumes:
      - ../:/app
      #Not support python 3.10
  # Sanic3.10:
  #   image: sanic-py-3.10
  #   build: 
  #     context: ..
  #     dockerfile: SanicApp/dockerfile
  #     args: 
  #       VERSION: "3.10"
  #   ports:
  #     - 7005:7000
  #     - 6005:6000
  #   volumes:
  #     - ../:/app
  #   environment:
  #       REVDEBUG_HOST: ${REVDEBUG_HOST:-20.199.127.147}
  #       DB_TEST_HOST: ${DB_TEST_HOST:-}
  #       DB_TEST_PORT: ${DB_TEST_PORT:-5432}
  #       DB_TEST_USER: ${DB_TEST_USER:-rdb_user}
  #       DB_TEST_PASS: ${DB_TEST_PASS:-masterkey}
  #       DB_TEST_DB: ${DB_TEST_DB:-revdebug_db}