ARG VERSION=3.9
FROM  python-revdebug:$VERSION
# FROM python:3.9-slim-buster
# FROM  docker-test.revdebug.com/python-revdebug:3.9
WORKDIR /app

RUN pip3 install django==2.2.0          ; \
    pip3 install flask                  ; \
    pip3 install tornado                ; \
    pip3 install sanic                  ; \
    pip3 install requests               ; \
    pip3 install aiohttp                ; \
    pip3 install pyramid                ; \
    pip3 install psycopg2-binary        ; \
    pip3 install celery==4.4.7          ; \
    pip3 install redis                  ; \
    pip3 install django-celery-beat     ; \
    pip3 install django-celery-results  ; \
    pip3 install PyMySQL                ; \
    pip3 install cryptography           ; \
    pip3 install pymongo                ; \   
    pip3 install  gitpython             ; \
    pip3 install numpy

ARG REVDEBUG_HOST_ARG=localhost
ENV REVDEBUG_HOST=$REVDEBUG_HOST_ARG
ENV REVDEBUG_EXC_STATUS=404