FROM  py-rdb:latest

WORKDIR /app

COPY ./tornado /app
COPY ./tests /app/tests

ENV REVDEBUG_SOLUTION=tornado
ENV REVDEBUG_APPLICATION=tornado

ENV REVDEBUG_MODE=crash
ENV REVDEBUG_HOST=20.188.58.169

ENV REVDEBUG_APM=1

CMD python app.py
