version: "3.0"
services:
  tornado:
    image: tornado-py
    build: 
      context: ..
      dockerfile: tornado/dockerfile
    ports:
      - 7000:7000
    volumes:
      - ../tornado:/app
      - ../tests:/app/tests
    