ARG VERSION=3.9
FROM python:$VERSION-slim-buster
# FROM python:3.9-slim-buster
# FROM  docker-test.revdebug.com/python-revdebug:3.9
WORKDIR /app

RUN pip3 install tornado  ; \
pip3 install requests

COPY . /app

CMD python app.py

