version: "3.0"
services:
  tornado:
    image: tornado-py
    build: 
      context: ..
      dockerfile: tornadoApp/dockerfile
    ports:
      - 7000:7000
      - 8999:8999
    volumes:
      - ../:/app
    