ARG VERSION=3.9
FROM  py-rdb:$VERSION

WORKDIR /app

COPY ./tornadoApp /app/tornadoApp
COPY ./tests /app/tests

ENV REVDEBUG_SOLUTION=TornadoTest \
 REVDEBUG_APPLICATION=TornadoTest \
 REVDEBUG_HOST=20.199.127.147 \
 REVDEBUG_APM=1 \
 REVDEBUG_LOGGING=debug \
 REVDEBUG_MODE=Live


CMD python tornadoApp/appTornado.py
