version: "3.0"
services:
  tornado3.8:
    image: tornado-py-3.8
    build: 
      context: ..
      dockerfile: tornadoApp/dockerfile
      args: 
        VERSION: 3.8
    ports:
      - 7000:7000
      - 6000:6000
    environment:
        REVDEBUG_HOST: ${REVDEBUG_HOST:-20.199.127.147}
        DB_TEST_HOST: ${DB_TEST_HOST:-}
        DB_TEST_PORT: ${DB_TEST_PORT:-5432}
        DB_TEST_USER: ${DB_TEST_USER:-rdb_user}
        DB_TEST_PASS: ${DB_TEST_PASS:-masterkey}
        DB_TEST_DB: ${DB_TEST_DB:-revdebug_db}
        REVDEBUG_SOLUTION: TornadoTest3.8
        REVDEBUG_APPLICATION: TornadoTest3.8
        SW_AGENT_LOG_REPORTER_LEVEL: INFO
        SW_AGENT_LOG_REPORTER_ACTIVE: "True"
    volumes:
      - ../:/app
  tornado3.9:
    image: tornado-py-3.9
    build: 
      context: ..
      dockerfile: tornadoApp/dockerfile
      args: 
        VERSION: 3.9
    environment:
        REVDEBUG_HOST: ${REVDEBUG_HOST:-gogopowerrangers.francecentral.cloudapp.azure.com}
        DB_TEST_HOST: ${DB_TEST_HOST:-}
        DB_TEST_PORT: ${DB_TEST_PORT:-5432}
        DB_TEST_USER: ${DB_TEST_USER:-rdb_user}
        DB_TEST_PASS: ${DB_TEST_PASS:-masterkey}
        DB_TEST_DB: ${DB_TEST_DB:-revdebug_db}
        REVDEBUG_SOLUTION: TornadoTest3.9
        REVDEBUG_APPLICATION: TornadoTest3.9
        SW_AGENT_LOG_REPORTER_LEVEL: INFO
        SW_AGENT_LOG_REPORTER_ACTIVE: "True"
    ports:
      - 7001:7000
      - 6001:6000
    volumes:
      - ../:/app
  tornado3.10:
    image: tornado-py-3.10
    build: 
      context: ..
      dockerfile: tornadoApp/dockerfile
      args: 
        VERSION: "3.10"
    ports:
      - 7002:7000
      - 6002:6000
    volumes:
      - ../:/app
    environment:
        REVDEBUG_HOST: ${REVDEBUG_HOST:-gogopowerrangers.francecentral.cloudapp.azure.com}
        DB_TEST_HOST: ${DB_TEST_HOST:-}
        DB_TEST_PORT: ${DB_TEST_PORT:-5432}
        DB_TEST_USER: ${DB_TEST_USER:-rdb_user}
        DB_TEST_PASS: ${DB_TEST_PASS:-masterkey}
        DB_TEST_DB: ${DB_TEST_DB:-revdebug_db}
        REVDEBUG_SOLUTION: TornadoTest3.10
        REVDEBUG_APPLICATION: TornadoTest3.10
        # SW_AGENT_LOG_REPORTER_LEVEL: INFO
        # SW_AGENT_LOG_REPORTER_ACTIVE: "True"