FROM  py-rdb:latest
WORKDIR /app

COPY ./appTornado.py /app/appTornado.py
COPY ./tornadoApp /app/tornadoApp
COPY ./tests /app/tests

ENV REVDEBUG_SOLUTION=tornado \
 REVDEBUG_APPLICATION=tornado \
 REVDEBUG_MODE=crash\
 REVDEBUG_HOST=20.199.127.147 \
 REVDEBUG_APM=1

CMD python appTornado.py
