version: "3.0"
services:
  tornado3.8:
    image: tornado-py-3.8
    build: 
      context: ..
      dockerfile: tornadoApp/dockerfile
      args: 
        VERSION: 3.8
    ports:
      - 7000:7000

    volumes:
      - ../:/app
  tornado3.9:
    image: tornado-py-3.9
    build: 
      context: ..
      dockerfile: tornadoApp/dockerfile
      args: 
        VERSION: 3.9
    ports:
      - 7001:7000
    volumes:
      - ../:/app
  tornado3.10:
    image: tornado-py-3.10
    build: 
      context: ..
      dockerfile: tornadoApp/dockerfile
      args: 
        VERSION: "3.10"
    ports:
      - 7002:7000
    volumes:
      - ../:/app